global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#artem_sereda'
