version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      back_net:
          aliases:
            - comment_db
            - post_db
      front_net:
  ui:
    image: ${USERNAME}/ui:${ui_version}
    ports:
      - ${ui_ext_port}:9292/tcp
    networks:
      - front_net
  post:
    image: ${USERNAME}/post:${post_version}
    networks:
      - front_net
      - back_net
  comment:
    image: ${USERNAME}/comment:${comment_version}
    networks:
      - front_net
      - back_net

volumes:
  post_db:
  prometheus_data:

networks:
  front_net:
  back_net:
