---
- name: Install Docker
  hosts: all
  become: true
  tags: docker-host

  vars:
    docker_edition: 'ce'
    docker_service_state: started
    docker_service_enabled: yes
    docker_install_compose: yes
    pip_install_packages:
      - name: docker
      - name: docker-compose
  roles:
    - geerlingguy.docker
    - geerlingguy.pip
