kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: 4d35yW1WFgY9z8sjOgbz9t+lZG5Ly/36qY7yD5Ke97k=
      - identity: {}
